# ============================================================================
# Key Vault — stores the ingest API key and the AAD app client secret
# ============================================================================
# NOTE: The Terraform identity needs Key Vault Administrator rights on this vault
# (granted below via RBAC).  The Function App's system-assigned managed identity
# is granted Key Vault Secrets User so it can read secrets at runtime.
# ============================================================================

data "azurerm_client_config" "current" {}

resource "azurerm_key_vault" "main" {
  name                       = local.keyvault_name
  resource_group_name        = azurerm_resource_group.main.name
  location                   = var.function_location
  tenant_id                  = var.tenant_id
  sku_name                   = "standard"
  rbac_authorization_enabled = true

  # Soft-delete is always on; purge-protection disabled for dev
  purge_protection_enabled = false

  tags = local.common_tags
}

# ── Random ingest API key ──────────────────────────────────────────────────

resource "random_password" "ingest_api_key" {
  length           = 48
  special          = false
  override_special = ""
}

resource "azurerm_key_vault_secret" "ingest_api_key" {
  name         = "dashboard-ingest-api-key"
  value        = random_password.ingest_api_key.result
  key_vault_id = azurerm_key_vault.main.id

  depends_on = [azurerm_role_assignment.terraform_kv_admin]
}

# ── AAD app client secret (generated by entra.tf) ─────────────────────────

resource "azurerm_key_vault_secret" "app_client_secret" {
  name         = "dashboard-app-client-secret"
  value        = azuread_application_password.dashboard.value
  key_vault_id = azurerm_key_vault.main.id

  depends_on = [azurerm_role_assignment.terraform_kv_admin]
}

# ── RBAC ──────────────────────────────────────────────────────────────────

# Terraform identity — manage secrets
resource "azurerm_role_assignment" "terraform_kv_admin" {
  scope                = azurerm_key_vault.main.id
  role_definition_name = "Key Vault Administrator"
  principal_id         = data.azurerm_client_config.current.object_id
}

# Function App managed identity — read secrets at runtime
resource "azurerm_role_assignment" "function_kv_secrets_user" {
  scope                = azurerm_key_vault.main.id
  role_definition_name = "Key Vault Secrets User"
  principal_id         = azurerm_linux_function_app.main.identity[0].principal_id
}
